exclude: "\\.patch$"
repos:
    - repo: https://github.com/NixOS/nixfmt
      rev: v1.1.0
      hooks:
            - id: nixfmt-nix
    - repo: https://github.com/scop/pre-commit-shfmt
      rev: v3.12.0-2
      hooks:
        - id: shfmt
          args: [--write, --simplify, --indent=2, --case-indent, --space-redirects]
    - repo: https://github.com/astro/deadnix
      rev: v1.3.1
      hooks:
        - id: deadnix
          args: [--edit, --no-lambda-arg]
          stages: [pre-commit]
