# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # fileSystems."/" =
  #   { device = "/dev/mapper/root_vg-root";
  #     fsType = "btrfs";
  #     options = [ "subvol=root" ];
  #   };

  # fileSystems."/nix" =
  #   { device = "/dev/mapper/root_vg-root";
  #     fsType = "btrfs";
  #     options = [ "subvol=nix" ];
  #   };

  # fileSystems."/persist" =
  #   { device = "/dev/mapper/root_vg-root";
  #     fsType = "btrfs";
  #     options = [ "subvol=persist" ];
  #   };

  # fileSystems."/boot" =
  #   { device = "/dev/disk/by-uuid/ACDC-204A";
  #     fsType = "vfat";
  #     options = [ "fmask=0022" "dmask=0022" ];
  #   };

  # fileSystems."/mnt/dataRoot" =
  #   { device = "/dev/disk/by-uuid/7a54cf21-8ca9-42a8-81eb-3af59543a5ee";
  #     fsType = "btrfs";
  #     options = [ "subvol=dataRoot" ];
  #   };

  swapDevices = [
    { device = "/dev/disk/by-uuid/13de4127-e807-4856-ae69-1c2653df8fbb"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
